import { useState, useMemo } from 'react'
import { useTheme } from '../context/ThemeContext'
import {
  X, Copy, Check, Radio, ChevronDown, ChevronRight,
  Plus, Trash2, Zap, Clock, Shield,
} from 'lucide-react'

// ─── Common target presets ────────────────────────────────────────────────────

const PRESETS = [
  { label: 'Node Exporter',  value: 'http://localhost:9100/metrics',  hint: 'Linux host metrics — CPU, memory, disk, network' },
  { label: 'cAdvisor',       value: 'http://localhost:8080/metrics',   hint: 'Docker / container resource usage' },
  { label: 'TSDB Self',      value: 'http://localhost:9102/metrics',   hint: 'TSDB.ai self-monitoring exporter' },
  { label: 'Postgres',       value: 'http://localhost:9187/metrics',   hint: 'postgres_exporter' },
  { label: 'Redis',          value: 'http://localhost:9121/metrics',   hint: 'redis_exporter' },
  { label: 'Nginx',          value: 'http://localhost:9113/metrics',   hint: 'nginx-prometheus-exporter' },
  { label: 'JVM / Micrometer', value: 'http://localhost:8090/actuator/prometheus', hint: 'Spring Boot / Micronaut actuator' },
  { label: 'Custom URL',     value: '',                                hint: 'Enter your own endpoint' },
]

const PLATFORMS = [
  { id: 'yaml',       label: 'YAML Config', icon: '📄' },
  { id: 'linux',      label: 'Linux',       icon: '🐧' },
  { id: 'macos',      label: 'macOS',       icon: '🍎' },
  { id: 'docker',     label: 'Docker',      icon: '🐳' },
  { id: 'kubernetes', label: 'Kubernetes',  icon: '☸️'  },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

function slug(name) {
  return (name || 'scraper').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'scraper'
}

function targetSlug(url) {
  try {
    const u = new URL(url)
    return u.hostname.replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'target'
  } catch {
    return 'target'
  }
}

// ─── Config generators ────────────────────────────────────────────────────────

function resolveTargets(f) {
  const filtered = f.targets?.filter(t => t.trim()) || []
  return filtered.length ? filtered : ['http://localhost:9100/metrics']
}

function yamlConfig(f, targetOverride) {
  const targets = targetOverride ? [targetOverride] : resolveTargets(f)
  const targetLines = targets.length === 1
    ? `  target_endpoint: "${targets[0]}"`
    : `  target_endpoints:\n${targets.map(t => `    - "${t}"`).join('\n')}`
  return `# TSDB.ai Scraper — ${f.name || 'unnamed'}
# Generated by TSDB.ai Admin Panel
scraper:
${targetLines}
  ingest_endpoint: "${f.ingestEndpoint || 'http://localhost:8080/ingest_samples'}"
  interval_s:      ${f.intervalS}
  timeout_s:       ${f.timeoutS}
  max_buffer_bytes: ${f.maxBufferBytes}${f.proxyUrl ? `\n  proxy_url: "${f.proxyUrl}"` : ''}`
}

function linuxScript(f) {
  const s = slug(f.name)
  const targets = resolveTargets(f)
  const multiTarget = targets.length > 1

  const serviceBlock = (dir) => `[Unit]
Description=TSDB.ai Scraper (${f.name || s})
After=network.target

[Service]
Type=simple
User=nobody
WorkingDirectory=${dir}
ExecStart=${dir}/tsdb-scraper
Restart=on-failure
RestartSec=5s
StandardOutput=journal
StandardError=journal
SyslogIdentifier=tsdb-scraper-${s}

[Install]
WantedBy=multi-user.target`

  if (!multiTarget) {
    const dir = `/opt/tsdb-ai-scraper-${s}`
    return `#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────
#  TSDB.ai Scraper — ${f.name || 'unnamed'} (Linux / systemd)
#  Scrapes: ${targets[0] || '(target not set)'}
#  Pushes to: ${f.ingestEndpoint}
# ────────────────────────────────────────────────────────────────
set -e

TSDB_SRC="/path/to/tsdb.ai/v0.9"   # ← your source directory
INSTALL_DIR="${dir}"

sudo mkdir -p "$INSTALL_DIR"
sudo cp "$TSDB_SRC"/{scraper_agent.go,config.go,banner.go} "$INSTALL_DIR/"

sudo tee "$INSTALL_DIR/tsdb.yaml" > /dev/null << 'YAML'
${yamlConfig(f)}
YAML

cd "$INSTALL_DIR"
sudo go build -o tsdb-scraper scraper_agent.go config.go banner.go

sudo tee /etc/systemd/system/tsdb-scraper-${s}.service > /dev/null << 'UNIT'
${serviceBlock(dir)}
UNIT

sudo systemctl daemon-reload
sudo systemctl enable tsdb-scraper-${s}
sudo systemctl start  tsdb-scraper-${s}

echo "✓ Scraper '${f.name || s}' running."
echo "  Logs:   journalctl -u tsdb-scraper-${s} -f"
echo "  Status: systemctl status tsdb-scraper-${s}"`
  }

  // Multi-target: one systemd service per target
  const blocks = targets.map((target, i) => {
    const ts = targetSlug(target)
    const svcName = `tsdb-scraper-${s}-${ts}`
    const dir = `/opt/tsdb-ai-scraper-${s}-${ts}`
    const singleF = { ...f, targets: [target] }
    return `# ── Target ${i + 1}: ${target}
sudo mkdir -p "${dir}"
sudo cp "$TSDB_SRC"/{scraper_agent.go,config.go,banner.go} "${dir}/"
sudo tee "${dir}/tsdb.yaml" > /dev/null << 'YAML'
${yamlConfig(singleF)}
YAML
cd "${dir}" && sudo go build -o tsdb-scraper scraper_agent.go config.go banner.go
sudo tee /etc/systemd/system/${svcName}.service > /dev/null << 'UNIT'
${serviceBlock(dir).replace(`SyslogIdentifier=tsdb-scraper-${s}`, `SyslogIdentifier=${svcName}`).replace(`Description=TSDB.ai Scraper (${f.name || s})`, `Description=TSDB.ai Scraper (${f.name} → ${ts})`)}
UNIT`
  }).join('\n\n')

  return `#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────
#  TSDB.ai Scraper — ${f.name || 'unnamed'} (Linux / systemd)
#  ${targets.length} targets → one systemd service each
#  All push to: ${f.ingestEndpoint}
# ────────────────────────────────────────────────────────────────
set -e
TSDB_SRC="/path/to/tsdb.ai/v0.9"   # ← your source directory

${blocks}

sudo systemctl daemon-reload
${targets.map(t => {
  const svcName = `tsdb-scraper-${s}-${targetSlug(t)}`
  return `sudo systemctl enable ${svcName} && sudo systemctl start ${svcName}`
}).join('\n')}

echo "✓ ${targets.length} scraper services started."`
}

function macosScript(f) {
  const s = slug(f.name)
  const targets = resolveTargets(f)
  const multiTarget = targets.length > 1

  const plistBlock = (label, bin, dir, logPath) => `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>${label}</string>
  <key>ProgramArguments</key>  <array><string>${bin}</string></array>
  <key>WorkingDirectory</key>  <string>${dir}</string>
  <key>RunAtLoad</key>         <true/>
  <key>KeepAlive</key>         <true/>
  <key>StandardOutPath</key>   <string>${logPath}</string>
  <key>StandardErrorPath</key> <string>${logPath}</string>
</dict>
</plist>`

  if (!multiTarget) {
    const label = `ai.tsdb.scraper.${s}`
    const dir   = `/usr/local/var/tsdb-ai-scraper-${s}`
    const bin   = `/usr/local/bin/tsdb-ai-scraper-${s}`
    const log   = `/usr/local/var/log/tsdb-ai-scraper-${s}.log`
    return `#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────
#  TSDB.ai Scraper — ${f.name || 'unnamed'} (macOS / launchd)
# ────────────────────────────────────────────────────────────────
set -e
TSDB_SRC="/path/to/tsdb.ai/v0.9"   # ← your source directory

cd "$TSDB_SRC"
go build -o /tmp/tsdb-ai-scraper-${s} scraper_agent.go config.go banner.go
sudo mv /tmp/tsdb-ai-scraper-${s} ${bin} && sudo chmod +x ${bin}

mkdir -p ${dir}
cat > ${dir}/tsdb.yaml << 'YAML'
${yamlConfig(f)}
YAML

mkdir -p ~/Library/LaunchAgents
cat > ~/Library/LaunchAgents/${label}.plist << 'PLIST'
${plistBlock(label, bin, dir, log)}
PLIST

launchctl load ~/Library/LaunchAgents/${label}.plist
launchctl start ${label}

echo "✓ Scraper running. Logs: tail -f ${log}"`
  }

  const blocks = targets.map((target, i) => {
    const ts    = targetSlug(target)
    const label = `ai.tsdb.scraper.${s}.${ts}`
    const dir   = `/usr/local/var/tsdb-ai-scraper-${s}-${ts}`
    const bin   = `/usr/local/bin/tsdb-ai-scraper-${s}-${ts}`
    const log   = `/usr/local/var/log/tsdb-ai-scraper-${s}-${ts}.log`
    const singleF = { ...f, targets: [target] }
    return `# Target ${i + 1}: ${target}
mkdir -p ${dir}
cat > ${dir}/tsdb.yaml << 'YAML'
${yamlConfig(singleF)}
YAML
cat > ~/Library/LaunchAgents/${label}.plist << 'PLIST'
${plistBlock(label, bin, dir, log)}
PLIST
launchctl load ~/Library/LaunchAgents/${label}.plist && launchctl start ${label}`
  }).join('\n\n')

  return `#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────
#  TSDB.ai Scraper — ${f.name || 'unnamed'} (macOS / launchd)
#  ${targets.length} targets → one launchd agent each
# ────────────────────────────────────────────────────────────────
set -e
TSDB_SRC="/path/to/tsdb.ai/v0.9"   # ← your source directory

# Build the shared binary once
cd "$TSDB_SRC"
go build -o /tmp/tsdb-ai-scraper scraper_agent.go config.go banner.go
mkdir -p ~/Library/LaunchAgents

${blocks}

echo "✓ ${targets.length} scraper agents loaded."`
}

function dockerCompose(f) {
  const s = slug(f.name)
  const targets = resolveTargets(f)

  const services = targets.map(target => {
    const ts = targetSlug(target)
    const svcName = targets.length === 1 ? `tsdb-scraper-${s}` : `tsdb-scraper-${s}-${ts}`
    const singleF = { ...f, targets: [target] }
    const cfgLines = yamlConfig(singleF).split('\n').map(l => '      ' + l).join('\n')
    return `  ${svcName}:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    image: tsdb-ai-scraper
    container_name: ${svcName}
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    configs:
      - source: ${svcName}-config
        target: /app/tsdb.yaml

configs:
  ${svcName}-config:
    content: |
${cfgLines}`
  }).join('\n\n')

  return `# ────────────────────────────────────────────────────────────────
#  TSDB.ai Scraper — ${f.name || 'unnamed'} (Docker Compose)
#  Run from your TSDB.ai v0.9 source directory:
#    docker compose -f docker-compose.scraper.yml up -d
# ────────────────────────────────────────────────────────────────

# First, create the Dockerfile (only needed once):
# cat > Dockerfile.scraper << 'EOF'
# FROM golang:1.22-alpine AS builder
# WORKDIR /app
# COPY scraper_agent.go config.go banner.go ./
# RUN go build -o tsdb-scraper scraper_agent.go config.go banner.go
# FROM alpine:latest
# WORKDIR /app
# COPY --from=builder /app/tsdb-scraper .
# CMD ["./tsdb-scraper"]
# EOF

# docker-compose.scraper.yml
services:
${services}`
}

function kubernetesYaml(f) {
  const s = slug(f.name)
  const targets = resolveTargets(f)

  const blocks = targets.map((target, i) => {
    const ts = targetSlug(target)
    const name = targets.length === 1 ? `tsdb-scraper-${s}` : `tsdb-scraper-${s}-${ts}`
    const singleF = { ...f, targets: [target] }
    const cfgLines = yamlConfig(singleF).split('\n').map(l => '    ' + l).join('\n')
    return `apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name}
  namespace: monitoring
data:
  tsdb.yaml: |
${cfgLines}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}
  namespace: monitoring
  labels:
    app: ${name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${name}
  template:
    metadata:
      labels:
        app: ${name}
    spec:
      containers:
      - name: scraper
        image: tsdb-ai-scraper:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests: { cpu: 50m, memory: 64Mi }
          limits:   { cpu: 200m, memory: 256Mi }
        volumeMounts:
        - name: config
          mountPath: /app/tsdb.yaml
          subPath: tsdb.yaml
      volumes:
      - name: config
        configMap:
          name: ${name}`
  })

  return `# ────────────────────────────────────────────────────────────────
#  TSDB.ai Scraper — ${f.name || 'unnamed'} (Kubernetes)
#  Build image first: docker build -f Dockerfile.scraper -t tsdb-ai-scraper .
#  Then: kubectl apply -f tsdb-scraper-${s}.yaml
# ────────────────────────────────────────────────────────────────
${blocks.join('\n---\n')}`
}

function generateConfig(form, platform) {
  switch (platform) {
    case 'yaml':       return yamlConfig(form)
    case 'linux':      return linuxScript(form)
    case 'macos':      return macosScript(form)
    case 'docker':     return dockerCompose(form)
    case 'kubernetes': return kubernetesYaml(form)
    default:           return ''
  }
}

// ─── UI helpers ───────────────────────────────────────────────────────────────

function Field({ label, hint, children }) {
  const { T } = useTheme()
  return (
    <div style={{ marginBottom: 14 }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: T.textSec, marginBottom: 3 }}>{label}</div>
      {hint && <div style={{ fontSize: 10, color: T.textMut, marginBottom: 5 }}>{hint}</div>}
      {children}
    </div>
  )
}

function Input({ value, onChange, placeholder, mono = false }) {
  const { T } = useTheme()
  return (
    <input
      value={value}
      onChange={e => onChange(e.target.value)}
      placeholder={placeholder}
      style={{
        width: '100%', boxSizing: 'border-box',
        padding: '8px 10px', borderRadius: 7,
        background: T.bgInput, border: `1px solid ${T.border}`,
        color: T.textPri, fontSize: 12,
        fontFamily: mono ? T.mono : 'inherit', outline: 'none',
      }}
    />
  )
}

function NumberInput({ value, onChange, min, step = 1 }) {
  const { T } = useTheme()
  return (
    <input
      type="number" min={min} step={step} value={value}
      onChange={e => onChange(Number(e.target.value))}
      style={{
        width: '100%', boxSizing: 'border-box',
        padding: '8px 10px', borderRadius: 7,
        background: T.bgInput, border: `1px solid ${T.border}`,
        color: T.textPri, fontSize: 12, fontFamily: T.mono, outline: 'none',
      }}
    />
  )
}

function CopyButton({ text }) {
  const { T } = useTheme()
  const [copied, setCopied] = useState(false)
  return (
    <button
      onClick={() => {
        navigator.clipboard.writeText(text).then(() => {
          setCopied(true); setTimeout(() => setCopied(false), 2000)
        })
      }}
      style={{
        display: 'flex', alignItems: 'center', gap: 5,
        padding: '6px 12px', borderRadius: 6, border: `1px solid ${T.border}`,
        background: copied ? `${T.green}22` : T.bgPanel,
        color: copied ? T.green : T.textSec, fontSize: 11, cursor: 'pointer',
        transition: 'all 0.2s',
      }}
    >
      {copied ? <Check size={11} /> : <Copy size={11} />}
      {copied ? 'Copied!' : 'Copy'}
    </button>
  )
}

// ─── Target row ───────────────────────────────────────────────────────────────

function TargetRow({ value, onChange, onRemove, canRemove, index }) {
  const { T } = useTheme()
  const [presetOpen, setPresetOpen] = useState(false)
  return (
    <div style={{ position: 'relative', marginBottom: 6 }}>
      <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
        <div style={{
          width: 18, height: 18, borderRadius: 5, flexShrink: 0,
          background: `${T.cyanL}18`, border: `1px solid ${T.cyanL}33`,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontSize: 9, fontWeight: 700, color: T.cyanL,
        }}>{index + 1}</div>
        <input
          value={value}
          onChange={e => onChange(e.target.value)}
          placeholder="http://host:9100/metrics"
          style={{
            flex: 1, padding: '7px 9px', borderRadius: 6,
            background: T.bgInput, border: `1px solid ${T.border}`,
            color: T.textPri, fontSize: 11, fontFamily: T.mono, outline: 'none',
          }}
        />
        <button
          onClick={() => setPresetOpen(o => !o)}
          title="Quick-fill"
          style={{
            width: 26, height: 26, flexShrink: 0, borderRadius: 6,
            background: T.bgPanel, border: `1px solid ${T.border}`,
            color: T.textMut, cursor: 'pointer', fontSize: 10,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}
        >
          <ChevronDown size={10} />
        </button>
        {canRemove && (
          <button
            onClick={onRemove}
            title="Remove"
            style={{
              width: 26, height: 26, flexShrink: 0, borderRadius: 6,
              background: T.bgPanel, border: `1px solid ${T.border}`,
              color: T.red, cursor: 'pointer',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}
          >
            <Trash2 size={10} />
          </button>
        )}
      </div>

      {presetOpen && (
        <div style={{
          position: 'absolute', top: '100%', left: 24, right: 0, zIndex: 30,
          background: T.bgCard, border: `1px solid ${T.border}`,
          borderRadius: 8, overflow: 'hidden',
          boxShadow: '0 8px 24px rgba(0,0,0,0.5)', marginTop: 2,
        }}>
          {PRESETS.map(p => (
            <div
              key={p.label}
              onClick={() => { if (p.value) onChange(p.value); setPresetOpen(false) }}
              style={{
                padding: '8px 12px', cursor: 'pointer',
                borderBottom: `1px solid ${T.border}`,
              }}
              onMouseEnter={e => { e.currentTarget.style.background = T.bgPanel }}
              onMouseLeave={e => { e.currentTarget.style.background = 'transparent' }}
            >
              <div style={{ fontSize: 11, fontWeight: 600, color: T.textPri }}>{p.label}</div>
              <div style={{ fontSize: 10, color: T.textMut }}>{p.hint}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function ScraperSetup({ onClose, onSave, existing }) {
  const { T } = useTheme()
  const initTargets = existing?.targets?.length
    ? existing.targets
    : (existing?.targetEndpoint ? [existing.targetEndpoint] : [''])

  const [form, setForm] = useState({
    id:             existing?.id             || crypto.randomUUID(),
    name:           existing?.name           || '',
    targets:        initTargets,
    ingestEndpoint: existing?.ingestEndpoint || 'http://localhost:8080/ingest_samples',
    intervalS:      existing?.intervalS      ?? 30,
    timeoutS:       existing?.timeoutS       ?? 20,
    maxBufferBytes: existing?.maxBufferBytes ?? 52428800,
    proxyUrl:       existing?.proxyUrl       || '',
  })

  const [platform, setPlatform] = useState('yaml')
  const [errors, setErrors]     = useState({})

  const set = (key, val) => setForm(f => ({ ...f, [key]: val }))

  const setTarget = (i, val) =>
    setForm(f => { const t = [...f.targets]; t[i] = val; return { ...f, targets: t } })

  const addTarget    = () => setForm(f => ({ ...f, targets: [...f.targets, ''] }))
  const removeTarget = (i) => setForm(f => ({ ...f, targets: f.targets.filter((_, j) => j !== i) }))

  const validate = () => {
    const e = {}
    if (!form.name.trim()) e.name = 'Name is required'
    if (!form.targets.some(t => t.trim())) e.targets = 'At least one target is required'
    if (!form.ingestEndpoint.trim()) e.ingestEndpoint = 'Ingest endpoint is required'
    setErrors(e)
    return Object.keys(e).length === 0
  }

  const generated = useMemo(() => generateConfig(form, platform), [form, platform])

  const activeTargets = form.targets.filter(t => t.trim()).length

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 1000,
      background: 'rgba(0,0,0,0.7)', backdropFilter: 'blur(4px)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      padding: 20,
    }}>
      <div style={{
        width: '100%', maxWidth: 1100, height: 'min(90vh, 800px)',
        background: T.bgCard, borderRadius: 16,
        border: `1px solid #28284a`,
        display: 'flex', flexDirection: 'column',
        boxShadow: '0 24px 80px rgba(0,0,0,0.6)',
        overflow: 'hidden',
      }}>

        {/* Header */}
        <div style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
          padding: '16px 22px', borderBottom: `1px solid ${T.border}`,
          background: T.bgPanel, flexShrink: 0,
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div style={{
              width: 32, height: 32, borderRadius: 9,
              background: `${T.cyanL}18`, border: `1px solid ${T.cyanL}33`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <Radio size={15} color={T.cyanL} />
            </div>
            <div>
              <div style={{ fontSize: 15, fontWeight: 700, color: T.textPri }}>
                {existing ? 'Edit Scraper' : 'Register New Scraper'}
              </div>
              <div style={{ fontSize: 11, color: T.textMut }}>
                Configure targets, generate launch scripts, register
              </div>
            </div>
          </div>
          <button onClick={onClose} style={{
            background: 'none', border: 'none', cursor: 'pointer',
            color: T.textMut, padding: 4, borderRadius: 6,
            display: 'flex', alignItems: 'center',
          }}>
            <X size={18} />
          </button>
        </div>

        {/* Body */}
        <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>

          {/* Left — form */}
          <div style={{
            width: 330, flexShrink: 0,
            borderRight: `1px solid ${T.border}`,
            overflowY: 'auto', padding: '18px 20px',
            display: 'flex', flexDirection: 'column',
          }}>

            {/* Name */}
            <Field label="Scraper Name" hint="Identifies this scraper in the UI">
              <Input value={form.name} onChange={v => set('name', v)} placeholder="e.g. prod-infra" />
              {errors.name && <div style={{ fontSize: 10, color: T.red, marginTop: 3 }}>{errors.name}</div>}
            </Field>

            {/* Targets */}
            <div style={{ marginBottom: 14 }}>
              <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                marginBottom: 3,
              }}>
                <div style={{ fontSize: 11, fontWeight: 700, color: T.textSec }}>
                  Scrape Targets
                </div>
                <span style={{ fontSize: 10, color: T.textMut }}>
                  {activeTargets} active
                </span>
              </div>
              <div style={{ fontSize: 10, color: T.textMut, marginBottom: 8 }}>
                Prometheus <code style={{ fontFamily: T.mono, color: T.cyanL }}>/metrics</code> endpoints to poll
              </div>

              {form.targets.map((target, i) => (
                <TargetRow
                  key={i}
                  index={i}
                  value={target}
                  onChange={v => setTarget(i, v)}
                  onRemove={() => removeTarget(i)}
                  canRemove={form.targets.length > 1}
                />
              ))}

              {errors.targets && (
                <div style={{ fontSize: 10, color: T.red, marginTop: 4 }}>{errors.targets}</div>
              )}

              <button
                onClick={addTarget}
                style={{
                  marginTop: 6, width: '100%',
                  padding: '6px 0', borderRadius: 6, cursor: 'pointer',
                  background: `${T.cyanL}0a`, border: `1px dashed ${T.cyanL}44`,
                  color: T.cyanL, fontSize: 11, fontWeight: 600,
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5,
                }}
              >
                <Plus size={11} /> Add Target
              </button>
            </div>

            {/* Ingest endpoint */}
            <Field label="Ingest Endpoint" hint="TSDB.ai ingestor — all targets push here">
              <Input
                value={form.ingestEndpoint}
                onChange={v => set('ingestEndpoint', v)}
                placeholder="http://localhost:8080/ingest_samples"
                mono
              />
              {errors.ingestEndpoint && (
                <div style={{ fontSize: 10, color: T.red, marginTop: 3 }}>{errors.ingestEndpoint}</div>
              )}
            </Field>

            {/* Interval + timeout */}
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
              <Field label="Interval (s)" hint="Scrape frequency">
                <NumberInput value={form.intervalS} onChange={v => set('intervalS', v)} min={1} />
              </Field>
              <Field label="Timeout (s)" hint="Per-request">
                <NumberInput value={form.timeoutS} onChange={v => set('timeoutS', v)} min={1} />
              </Field>
            </div>

            {/* Buffer */}
            <Field label="Max Buffer (bytes)" hint="Resiliency buffer when ingestor is unreachable">
              <NumberInput value={form.maxBufferBytes} onChange={v => set('maxBufferBytes', v)} min={0} step={1048576} />
              <div style={{ fontSize: 10, color: T.textMut, marginTop: 3 }}>
                {form.maxBufferBytes >= 1073741824
                  ? (form.maxBufferBytes / 1073741824).toFixed(1) + ' GB'
                  : form.maxBufferBytes >= 1048576
                  ? (form.maxBufferBytes / 1048576).toFixed(0) + ' MB'
                  : (form.maxBufferBytes / 1024).toFixed(0) + ' KB'}
              </div>
            </Field>

            {/* Proxy */}
            <Field label="Proxy URL" hint="Optional — HTTP, HTTPS, or SOCKS5">
              <Input
                value={form.proxyUrl}
                onChange={v => set('proxyUrl', v)}
                placeholder="socks5://user:pass@proxy:1080"
                mono
              />
            </Field>

            {/* Summary strip */}
            <div style={{ flex: 1 }} />
            <div style={{
              marginTop: 12, padding: '10px 12px', borderRadius: 9,
              background: T.bgPanel, border: `1px solid ${T.border}`,
              display: 'flex', flexDirection: 'column', gap: 5,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
                <Radio size={10} color={T.textMut} />
                <span style={{ fontSize: 10, color: T.textMut }}>
                  {activeTargets} target{activeTargets !== 1 ? 's' : ''} → {form.ingestEndpoint || '(ingest not set)'}
                </span>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
                <Clock size={10} color={T.textMut} />
                <span style={{ fontSize: 10, color: T.textMut, fontFamily: T.mono }}>
                  every {form.intervalS}s · timeout {form.timeoutS}s
                </span>
              </div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
                <Zap size={10} color={T.textMut} />
                <span style={{ fontSize: 10, color: T.textMut, fontFamily: T.mono }}>
                  buffer {form.maxBufferBytes >= 1048576
                    ? (form.maxBufferBytes / 1048576).toFixed(0) + ' MB'
                    : (form.maxBufferBytes / 1024).toFixed(0) + ' KB'}
                </span>
              </div>
            </div>

            {/* Register button */}
            <button
              onClick={() => validate() && onSave(form)}
              style={{
                marginTop: 12, padding: '10px 0', borderRadius: 8,
                border: 'none', cursor: 'pointer',
                background: `linear-gradient(135deg, ${T.cyan}, ${T.purple})`,
                color: '#fff', fontSize: 13, fontWeight: 600,
                display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7,
              }}
            >
              <Shield size={13} />
              {existing ? 'Save Changes' : 'Register Scraper'}
              <ChevronRight size={13} />
            </button>
          </div>

          {/* Right — config preview */}
          <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>

            {/* Platform tabs */}
            <div style={{
              display: 'flex', borderBottom: `1px solid ${T.border}`,
              padding: '0 4px', flexShrink: 0, background: T.bgPanel,
            }}>
              {PLATFORMS.map(p => (
                <button
                  key={p.id}
                  onClick={() => setPlatform(p.id)}
                  style={{
                    padding: '10px 14px', border: 'none', cursor: 'pointer',
                    background: 'none', fontSize: 12, fontWeight: 600,
                    color: platform === p.id ? T.cyanL : T.textMut,
                    borderBottom: `2px solid ${platform === p.id ? T.cyanL : 'transparent'}`,
                    transition: 'color 0.15s',
                    display: 'flex', alignItems: 'center', gap: 5,
                  }}
                >
                  <span>{p.icon}</span>
                  {p.label}
                </button>
              ))}
            </div>

            {/* Platform description */}
            <div style={{
              padding: '9px 18px', borderBottom: `1px solid ${T.border}`,
              background: `${T.bgPanel}88`, flexShrink: 0,
            }}>
              {activeTargets > 1 && platform !== 'yaml' && (
                <span style={{ fontSize: 11, color: T.amber, marginRight: 8 }}>
                  ✦ {activeTargets} targets →
                </span>
              )}
              {{
                yaml:       <span style={{ fontSize: 11, color: T.textMut }}>Drop this into your <code style={{ fontFamily: T.mono, color: T.cyanL, background: T.bgInput, padding: '1px 5px', borderRadius: 4 }}>tsdb.yaml</code> and run the scraper binary.</span>,
                linux:      <span style={{ fontSize: 11, color: T.textMut }}>Installs {activeTargets > 1 ? `${activeTargets} <strong>systemd services</strong>, one per target` : 'a <strong>systemd service</strong>'}. Auto-starts on boot, restarts on crash.</span>,
                macos:      <span style={{ fontSize: 11, color: T.textMut }}>Installs {activeTargets > 1 ? `${activeTargets} <strong>launchd agents</strong>, one per target` : 'a <strong>launchd agent</strong>'}. Starts at login, restarts on crash.</span>,
                docker:     <span style={{ fontSize: 11, color: T.textMut }}>Docker Compose file — <code style={{ fontFamily: T.mono, color: T.cyanL, background: T.bgInput, padding: '1px 5px', borderRadius: 4 }}>docker compose up -d</code> to launch all services. Image: <code style={{ fontFamily: T.mono, color: T.cyanL, background: T.bgInput, padding: '1px 5px', borderRadius: 4 }}>tsdb-ai-scraper</code>.</span>,
                kubernetes: <span style={{ fontSize: 11, color: T.textMut }}>ConfigMap + Deployment in the <code style={{ fontFamily: T.mono, color: T.cyanL, background: T.bgInput, padding: '1px 5px', borderRadius: 4 }}>monitoring</code> namespace. Image: <code style={{ fontFamily: T.mono, color: T.cyanL, background: T.bgInput, padding: '1px 5px', borderRadius: 4 }}>tsdb-ai-scraper:latest</code>.</span>,
              }[platform]}
            </div>

            {/* Code block */}
            <div style={{ flex: 1, position: 'relative', overflow: 'hidden' }}>
              <div style={{ position: 'absolute', top: 10, right: 14, zIndex: 5 }}>
                <CopyButton text={generated} />
              </div>
              <pre style={{
                margin: 0, padding: '14px 16px',
                height: '100%', overflowY: 'auto', boxSizing: 'border-box',
                fontFamily: T.mono, fontSize: 11.5, lineHeight: 1.65,
                color: T.textSec, background: T.bgRoot,
                whiteSpace: 'pre-wrap', wordBreak: 'break-all',
              }}>
                {generated}
              </pre>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
