#!/usr/bin/env bash
# setup.sh — First-time install helper for tsdb.ai (bare Linux, no Docker)
#
# What it does:
#   1. Asks where you want to store TSDB runtime data (WAL, blocks, index, etc.)
#   2. Writes that path into tsdb.yaml as data.root
#   3. Creates the full directory tree under that path
#   4. Optionally builds all service binaries (requires Go 1.21+)
#
# Re-running this script is safe — it will not overwrite an existing tsdb.yaml
# unless you explicitly choose to do so.
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "${CYAN}[setup]${RESET} $*"; }
ok()      { echo -e "${GREEN}[setup]${RESET} $*"; }
warn()    { echo -e "${YELLOW}[setup]${RESET} $*"; }
die()     { echo -e "${RED}[setup] ERROR:${RESET} $*" >&2; exit 1; }

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BOLD}  tsdb.ai — First-time setup${RESET}"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/tsdb.yaml"

# ── Check for existing config ─────────────────────────────────────────────────
if [[ -f "${CONFIG_FILE}" ]]; then
    warn "tsdb.yaml already exists at ${CONFIG_FILE}"
    echo ""
    read -rp "  Overwrite it with new settings? [y/N]: " overwrite
    if [[ ! "${overwrite}" =~ ^[Yy]$ ]]; then
        info "Keeping existing tsdb.yaml. Run with a fresh copy to reconfigure."
        echo ""
        # Still offer to create missing directories and build binaries
        SKIP_CONFIG=true
    else
        SKIP_CONFIG=false
        cp "${CONFIG_FILE}" "${CONFIG_FILE}.bak"
        ok "Backed up existing config to tsdb.yaml.bak"
    fi
else
    SKIP_CONFIG=false
fi

# ── Choose data directory ─────────────────────────────────────────────────────
if [[ "${SKIP_CONFIG}" == false ]]; then
    echo ""
    echo -e "${BOLD}Where should tsdb.ai store its runtime data?${RESET}"
    echo "  This includes the WAL, canonical blocks, index, event logs,"
    echo "  pattern registry, and S3 upload manifest."
    echo ""
    echo "  Recommended locations:"
    echo "    /var/lib/tsdb.ai      (system service, survives reboots)"
    echo "    ~/tsdb.ai-data        (single-user / development)"
    echo "    ./tsdb.ai-data        (next to source, for local testing)"
    echo ""
    read -rp "  Data directory [default: /var/lib/tsdb.ai]: " DATA_ROOT
    DATA_ROOT="${DATA_ROOT:-/var/lib/tsdb.ai}"

    # Expand ~ if present
    DATA_ROOT="${DATA_ROOT/#\~/${HOME}}"
    # Strip trailing slash
    DATA_ROOT="${DATA_ROOT%/}"

    echo ""
    info "Data root will be: ${DATA_ROOT}"
fi

# ── Read data root from existing config if skipping ───────────────────────────
if [[ "${SKIP_CONFIG}" == true ]]; then
    DATA_ROOT=$(grep -E '^\s*root:' "${CONFIG_FILE}" | head -1 | sed 's/.*root:\s*//' | tr -d '"' | tr -d "'" | xargs)
    DATA_ROOT="${DATA_ROOT:-/var/lib/tsdb.ai}"
    DATA_ROOT="${DATA_ROOT/#\~/${HOME}}"
    info "Using existing data root: ${DATA_ROOT}"
fi

# ── Create directory tree ─────────────────────────────────────────────────────
echo ""
info "Creating directory structure under ${DATA_ROOT} ..."

DIRS=(
    "${DATA_ROOT}/wal"
    "${DATA_ROOT}/blocks/staging"
    "${DATA_ROOT}/blocks/canonical"
    "${DATA_ROOT}/index"
    "${DATA_ROOT}/events/anomalies"
    "${DATA_ROOT}/events/regimes"
    "${DATA_ROOT}/registry"
)

for d in "${DIRS[@]}"; do
    mkdir -p "${d}"
    ok "  created  ${d}"
done

# ── Write tsdb.yaml ───────────────────────────────────────────────────────────
if [[ "${SKIP_CONFIG}" == false ]]; then
    # Preserve everything after the data.root line from the template,
    # but swap in the chosen data root.
    if [[ -f "${CONFIG_FILE}.bak" ]]; then
        # Editing an existing file — replace the root: line in-place
        sed -i.tmp "s|^  root:.*|  root: ${DATA_ROOT}|" "${CONFIG_FILE}"
        rm -f "${CONFIG_FILE}.tmp"
    else
        # No existing file — write a minimal config that sources tsdb.yaml defaults
        # and only overrides data.root so all other defaults stay in effect.
        cat > "${CONFIG_FILE}" <<YAML
# tsdb.ai configuration — generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Edit this file to customise ports, S3 credentials, retention windows, etc.
# Full documentation: see tsdb.yaml.example or the inline comments in each section.

data:
  root: ${DATA_ROOT}

# ── Everything below inherits built-in defaults. ─────────────────────────────
# Uncomment and edit sections as needed.

# server:
#   ingest_port: 8080
#   query_port:  8081
#   vector_port: 8085

# s3:
#   enabled: false
#   endpoint: ""
#   region: us-east-1
#   bucket: ""
#   access_key_id: ""
#   secret_access_key: ""
#   retention_after_upload_min: 86400   # 60 days local copy
YAML
    fi
    ok "tsdb.yaml written → ${CONFIG_FILE}"
fi

# ── Permissions reminder ──────────────────────────────────────────────────────
if [[ "${DATA_ROOT}" == /var/lib/* ]]; then
    echo ""
    warn "Data root is under /var/lib — ensure the user running the services"
    warn "has read/write access:"
    warn "  sudo chown -R \$(whoami) ${DATA_ROOT}"
fi

# ── Optional: build binaries ──────────────────────────────────────────────────
echo ""
read -rp "Build all service binaries now? (requires Go 1.21+) [y/N]: " do_build

if [[ "${do_build}" =~ ^[Yy]$ ]]; then
    command -v go >/dev/null 2>&1 || die "Go not found in PATH. Install Go 1.21+ and re-run."
    GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
    info "Go version: ${GO_VERSION}"
    echo ""

    cd "${SCRIPT_DIR}"

    build() {
        local name="$1"; shift
        info "Building ${name} ..."
        go build -o "${name}" "$@"
        ok "  → ${name}"
    }

    build tsdb_ingestor \
        main.go model_compressor.go local_cleaner.go \
        pattern_registry.go causal_engine.go relationship_graph.go \
        vector_store.go forecasting.go s3_client.go s3_manifest.go config.go

    build deduper_service \
        deduper_service.go s3_client.go s3_manifest.go config.go

    build query_gateway \
        query_gateway.go s3_client.go s3_manifest.go config.go

    build wal_shipper \
        wal_shipper.go model_compressor.go local_cleaner.go config.go

    build tsdb_self_exporter \
        tsdb_self_exporter.go config.go

    build scraper_agent \
        scraper_agent.go config.go

    build vector_service \
        query_vector.go vector_store.go config.go

    echo ""
    ok "All binaries built successfully."
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
ok "Setup complete!"
echo ""
echo "  Data directory : ${DATA_ROOT}"
echo "  Config file    : ${CONFIG_FILE}"
echo ""
echo "  To start all services:"
echo "    supervisord -c supervisord.conf"
echo ""
echo "  To start a single service manually:"
echo "    ./tsdb_ingestor"
echo "    ./query_gateway"
echo "    ./deduper_service"
echo ""
echo "  To reconfigure, edit tsdb.yaml directly or re-run ./setup.sh"
echo -e "${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo ""
