apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsdb-server.fullname" . }}
  namespace: {{ include "tsdb-server.namespace" . }}
  labels:
    {{- include "tsdb-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "tsdb-server.selectorLabels" . | nindent 4 }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
    {{- end }}
