apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsdb-ui.fullname" . }}
  namespace: {{ include "tsdb-ui.namespace" . }}
  labels:
    {{- include "tsdb-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "tsdb-ui.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
