import { useEffect, useState, useCallback } from 'react'
import { useTheme } from '../context/ThemeContext'
import { fetchSystemMetrics, fetchForecastAll, fetchAnomalies, checkBackendOnline } from '../api'
import { Activity, Zap, AlertTriangle, Database, TrendingUp, TrendingDown, Minus, RefreshCw, Wifi, WifiOff, Copy, Check, Settings, ChevronDown, ChevronUp } from 'lucide-react'
import GetStarted from '../components/GetStarted'

// ─── Config generator ─────────────────────────────────────────────────────────

function ConfigGenerator() {
  const { T } = useTheme()
  const [open, setOpen] = useState(false)
  const [copied, setCopied] = useState(false)

  // Config fields with defaults matching config.go
  const [dataRoot,       setDataRoot]       = useState('./tsdb.ai-data')
  const [ingestPort,     setIngestPort]     = useState(8080)
  const [queryPort,      setQueryPort]      = useState(8081)
  const [rmse,           setRmse]           = useState(10.0)
  const [rmseMultiplier, setRmseMultiplier] = useState(3.0)
  const [s3Enabled,      setS3Enabled]      = useState(false)
  const [s3Endpoint,     setS3Endpoint]     = useState('')
  const [s3Region,       setS3Region]       = useState('us-east-1')
  const [s3Bucket,       setS3Bucket]       = useState('tsdb-ai-lts')
  const [s3Key,          setS3Key]          = useState('')
  const [s3Secret,       setS3Secret]       = useState('')
  const [mockInterval,   setMockInterval]   = useState(30)

  const yaml = `# tsdb.yaml — generated by TSDB.ai admin panel
# Place this file in the same directory as your Go source files (v0.9/).

server:
  ingest_port: ${ingestPort}
  query_port:  ${queryPort}
  deduper_endpoint: "http://localhost:8084/ingest_block"
  vector_db_endpoint: "http://localhost:8085/ingest"

data:
  root: "${dataRoot}"

ingestion:
  rmse_tolerance: ${rmse}
  num_shards: 256
  wal_batch_size: 500
  wal_batch_interval_ms: 200

anomaly:
  rmse_multiplier: ${rmseMultiplier}
  min_chunks_for_history: 5
  seasonal_slots: 168

scraper:
  target_endpoint: "http://localhost:9102/metrics"
  ingest_endpoint: "http://localhost:${ingestPort}/ingest_samples"
  interval_s: ${mockInterval}
  timeout_s: 20
${s3Enabled ? `
s3:
  enabled: true
  endpoint: "${s3Endpoint}"
  region: "${s3Region}"
  bucket: "${s3Bucket}"
  prefix: "blocks/"
  access_key_id: "${s3Key}"
  secret_access_key: "${s3Secret}"
  use_path_style: ${s3Endpoint ? 'true' : 'false'}
  upload_workers: 4
  upload_timeout_s: 60
  download_timeout_s: 30
  retention_after_upload_min: 86400
` : `
s3:
  enabled: false
`}`

  const copy = () => {
    navigator.clipboard.writeText(yaml)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const inp = (val, set, type = 'text') => ({
    value: val,
    onChange: e => set(type === 'number' ? parseFloat(e.target.value) || 0 : e.target.value),
    type,
    style: {
      width: '100%', boxSizing: 'border-box',
      padding: '6px 9px', borderRadius: 6,
      border: `1px solid ${T.border}`, background: '#0d1117',
      color: T.textPri, fontSize: 11, fontFamily: T.mono, outline: 'none',
    },
  })

  const row = (label, children) => (
    <div style={{ display: 'grid', gridTemplateColumns: '140px 1fr', alignItems: 'center', gap: 8, marginBottom: 7 }}>
      <span style={{ fontSize: 11, color: T.textMut }}>{label}</span>
      {children}
    </div>
  )

  return (
    <div style={{ marginTop: 16 }}>
      {/* Toggle header */}
      <button
        onClick={() => setOpen(o => !o)}
        style={{
          width: '100%', display: 'flex', alignItems: 'center', gap: 8,
          padding: '9px 12px', borderRadius: 8,
          border: `1px solid ${T.border}`, background: T.bgCard,
          color: T.textSec, fontSize: 12, cursor: 'pointer',
        }}
      >
        <Settings size={13} color={T.purple} />
        <span style={{ flex: 1, textAlign: 'left', fontWeight: 600 }}>Generate tsdb.yaml config file</span>
        {open ? <ChevronUp size={13} color={T.textMut} /> : <ChevronDown size={13} color={T.textMut} />}
      </button>

      {open && (
        <div style={{
          marginTop: 6, padding: '16px', borderRadius: 8,
          border: `1px solid ${T.border}`, background: T.bgCard,
        }}>
          {/* ── Basic settings ── */}
          <div style={{ fontSize: 10, fontWeight: 700, color: T.textMut, letterSpacing: '0.08em', marginBottom: 10 }}>BASIC</div>
          {row('Data directory',  <input {...inp(dataRoot, setDataRoot)} />)}
          {row('Ingest port',     <input {...inp(ingestPort, setIngestPort, 'number')} />)}
          {row('Query port',      <input {...inp(queryPort, setQueryPort, 'number')} />)}
          {row('RMSE tolerance',  <input {...inp(rmse, setRmse, 'number')} />)}
          {row('RMSE multiplier', <input {...inp(rmseMultiplier, setRmseMultiplier, 'number')} />)}

          {/* ── S3 toggle ── */}
          <div style={{ fontSize: 10, fontWeight: 700, color: T.textMut, letterSpacing: '0.08em', margin: '14px 0 10px' }}>S3 LONG-TERM STORAGE</div>
          <label style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10, cursor: 'pointer', fontSize: 11, color: T.textSec }}>
            <input type="checkbox" checked={s3Enabled} onChange={e => setS3Enabled(e.target.checked)}
              style={{ accentColor: T.purple }} />
            Enable S3 / object storage
          </label>
          {s3Enabled && <>
            {row('Endpoint URL',   <input {...inp(s3Endpoint, setS3Endpoint)} placeholder="leave blank for AWS" />)}
            {row('Region',         <input {...inp(s3Region, setS3Region)} />)}
            {row('Bucket',         <input {...inp(s3Bucket, setS3Bucket)} />)}
            {row('Access Key ID',  <input {...inp(s3Key, setS3Key)} />)}
            {row('Secret Key',     <input {...inp(s3Secret, setS3Secret, 'password')} />)}
          </>}

          {/* ── Preview + copy ── */}
          <div style={{ marginTop: 14, position: 'relative' }}>
            <pre style={{
              fontFamily: T.mono, fontSize: 10,
              background: '#0d1117', border: `1px solid ${T.border}`,
              borderRadius: 6, padding: '10px 12px', color: '#7ee787',
              lineHeight: 1.7, overflowX: 'auto', maxHeight: 200,
              overflowY: 'auto', margin: 0, userSelect: 'all',
            }}>{yaml}</pre>
            <button
              onClick={copy}
              style={{
                position: 'absolute', top: 7, right: 7,
                display: 'flex', alignItems: 'center', gap: 4,
                padding: '4px 9px', borderRadius: 5, border: 'none', cursor: 'pointer',
                background: copied ? T.green : T.purple,
                color: '#fff', fontSize: 10, fontWeight: 600,
                transition: 'background 0.2s',
              }}
            >
              {copied ? <Check size={10} /> : <Copy size={10} />}
              {copied ? 'Copied!' : 'Copy'}
            </button>
          </div>
          <div style={{ marginTop: 8, fontSize: 10, color: T.textMut }}>
            Save as <code style={{ fontFamily: T.mono, color: T.cyan }}>tsdb.yaml</code> in the same directory as the Go source files. The server will pick it up on next start.
          </div>
        </div>
      )}
    </div>
  )
}

// ─── No-backend modal ─────────────────────────────────────────────────────────

function NoBackendModal({ onRetry, checking }) {
  const { T } = useTheme()
  const CMD_STYLE = {
    fontFamily: T.mono,
    fontSize: 12,
    background: '#0d1117',
    border: `1px solid ${T.border}`,
    borderRadius: 7,
    padding: '9px 14px',
    color: '#7ee787',
    lineHeight: 1.8,
    userSelect: 'all',
    marginBottom: 8,
    overflowX: 'auto',
    whiteSpace: 'pre',
  }

  return (
    <div style={{
      position: 'fixed', inset: 0, zIndex: 1000,
      background: 'rgba(0,0,0,0.72)',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      backdropFilter: 'blur(4px)',
      overflowY: 'auto', padding: '24px 0',
    }}>
      <div style={{
        background: T.bgPanel,
        border: `1px solid ${T.border}`,
        borderRadius: 14,
        padding: '28px 32px',
        maxWidth: 560,
        width: '90vw',
        boxShadow: '0 24px 64px rgba(0,0,0,0.5)',
        margin: 'auto',
      }}>
        {/* Icon + title */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 16 }}>
          <div style={{
            width: 46, height: 46, borderRadius: 12, flexShrink: 0,
            background: `${T.red}18`, border: `1px solid ${T.red}44`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <WifiOff size={22} color={T.red} />
          </div>
          <div>
            <div style={{ fontSize: 17, fontWeight: 700, color: T.textPri }}>Backend not running</div>
            <div style={{ fontSize: 12, color: T.textMut, marginTop: 3 }}>
              No connection to the TSDB server on <code style={{ fontFamily: T.mono, color: T.cyan }}>localhost:8080</code>
            </div>
          </div>
        </div>

        <div style={{ fontSize: 12, color: T.textSec, marginBottom: 16, lineHeight: 1.6 }}>
          Run these scripts from the <code style={{ fontFamily: T.mono, color: T.cyan, fontSize: 11 }}>v0.9/</code> directory,
          then click <strong style={{ color: T.textPri }}>Retry Connection</strong>.
        </div>

        {/* ── Step 0: make executable (first time only) ── */}
        <div style={{ fontSize: 11, color: T.textMut, fontWeight: 700, letterSpacing: '0.08em', marginBottom: 6 }}>
          FIRST TIME — Make scripts executable
        </div>
        <div style={CMD_STYLE}>{'chmod +x ./install/local/start-server.sh ./install/local/start-mock.sh ./install/local/start-ui.sh'}</div>

        {/* ── Step 1: server ── */}
        <div style={{ fontSize: 11, color: T.textMut, fontWeight: 700, letterSpacing: '0.08em', marginBottom: 6, marginTop: 12 }}>
          TERMINAL 1 — Server + query gateway
        </div>
        <div style={CMD_STYLE}>./install/local/start-server.sh</div>

        {/* ── Step 2: mock (optional) ── */}
        <div style={{ fontSize: 11, color: T.textMut, fontWeight: 700, letterSpacing: '0.08em', marginBottom: 6, marginTop: 12 }}>
          TERMINAL 2 — Mock data&nbsp;
          <span style={{ fontWeight: 400, color: T.textMut }}>(optional — skip if you have real metrics)</span>
        </div>
        <div style={CMD_STYLE}>./install/local/start-mock.sh</div>

        {/* ── Config generator ── */}
        <ConfigGenerator />

        {/* ── Retry ── */}
        <button
          onClick={onRetry}
          disabled={checking}
          style={{
            marginTop: 14,
            width: '100%', padding: '11px', borderRadius: 8, border: 'none',
            background: checking ? T.bgCard : `linear-gradient(135deg, ${T.purple}, ${T.cyan})`,
            color: checking ? T.textMut : '#fff',
            fontSize: 13, fontWeight: 600, cursor: checking ? 'not-allowed' : 'pointer',
            display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
            transition: 'all 0.2s',
          }}
        >
          <RefreshCw size={14} style={{ animation: checking ? 'spin 1s linear infinite' : 'none' }} />
          {checking ? 'Checking…' : 'Retry Connection'}
        </button>
      </div>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )
}

// ─── Tooltip ─────────────────────────────────────────────────────────────────

function Tooltip({ text }) {
  const { T } = useTheme()
  const [show, setShow] = useState(false)
  return (
    <div style={{ position: 'relative', display: 'inline-flex', alignItems: 'center' }}>
      <div
        onMouseEnter={() => setShow(true)}
        onMouseLeave={() => setShow(false)}
        style={{
          width: 15, height: 15, borderRadius: '50%', flexShrink: 0,
          background: `${T.textMut}22`, border: `1px solid ${T.textMut}44`,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          cursor: 'default', fontSize: 9, fontWeight: 700, color: T.textMut,
          userSelect: 'none',
        }}
      >?</div>
      {show && (
        <div style={{
          position: 'absolute', bottom: 'calc(100% + 7px)', left: '50%',
          transform: 'translateX(-50%)',
          background: '#1a1a2e', border: `1px solid ${T.border}`,
          borderRadius: 8, padding: '9px 12px',
          fontSize: 11, color: T.textSec, lineHeight: 1.6,
          width: 230, zIndex: 100, pointerEvents: 'none',
          boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
          whiteSpace: 'normal',
        }}>
          {text}
          {/* Caret */}
          <div style={{
            position: 'absolute', top: '100%', left: '50%', transform: 'translateX(-50%)',
            width: 0, height: 0,
            borderLeft: '6px solid transparent',
            borderRight: '6px solid transparent',
            borderTop: `6px solid ${T.border}`,
          }} />
        </div>
      )}
    </div>
  )
}

// ─── Stat cards ───────────────────────────────────────────────────────────────

// ─── Byte formatter ───────────────────────────────────────────────────────────

function fmtBytes(bytes) {
  if (bytes == null || isNaN(bytes)) return '—'
  const units = ['B', 'KB', 'MB', 'GB', 'TB', 'PB']
  let val = bytes
  let i = 0
  while (val >= 1024 && i < units.length - 1) {
    val /= 1024
    i++
  }
  const formatted = i === 0
    ? val.toFixed(0)
    : val >= 100 ? val.toFixed(1) : val.toFixed(2)
  return `${formatted} ${units[i]}`
}

function StatCard({ label, value, sub, color, icon: Icon, glow: g, tooltip }) {
  const { T } = useTheme()
  const c = color || T.cyan
  return (
    <div style={{
      background: T.bgCard, borderRadius: 12, padding: '18px 20px',
      border: `1px solid ${T.border}`,
      boxShadow: g || 'none',
    }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginBottom: 8 }}>
            <div style={{ fontSize: 11, color: T.textMut, letterSpacing: '0.07em', fontWeight: 600 }}>
              {label.toUpperCase()}
            </div>
            {tooltip && <Tooltip text={tooltip} />}
          </div>
          <div style={{ fontSize: 26, fontWeight: 700, color: c, fontFamily: T.mono, lineHeight: 1 }}>
            {value}
          </div>
          {sub && <div style={{ fontSize: 11, color: T.textSec, marginTop: 6 }}>{sub}</div>}
        </div>
        {Icon && (
          <div style={{
            width: 38, height: 38, borderRadius: 10, flexShrink: 0,
            background: `${c}18`, border: `1px solid ${c}33`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
          }}>
            <Icon size={18} color={c} />
          </div>
        )}
      </div>
    </div>
  )
}

function ForecastRow({ f }) {
  const { T } = useTheme()
  const delta = f.predicted_value - f.current_value
  const TrendIcon = Math.abs(delta) < 0.5 ? Minus : delta > 0 ? TrendingUp : TrendingDown
  const color = Math.abs(delta) < 0.5 ? T.textSec : delta > 0 ? T.amber : T.green
  const qualityColor = { HIGH: T.green, MEDIUM: T.amber, LOW: T.red }[f.forecast_quality] || T.textMut

  return (
    <div style={{
      display: 'flex', alignItems: 'center', gap: 12,
      padding: '10px 14px', borderRadius: 8,
      background: T.bgPanel, border: `1px solid ${T.border}`,
      marginBottom: 6,
    }}>
      <TrendIcon size={14} color={color} />
      <span style={{ flex: 1, fontSize: 12, color: T.textSec, fontFamily: T.mono, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
        {f.metric}
      </span>
      <span style={{ fontSize: 12, color: T.textPri, fontFamily: T.mono, minWidth: 60, textAlign: 'right' }}>
        {f.current_value.toFixed(2)}
      </span>
      <span style={{ fontSize: 11, color, minWidth: 54, textAlign: 'right', fontFamily: T.mono }}>
        {delta >= 0 ? '+' : ''}{delta.toFixed(2)}
      </span>
      <span style={{
        fontSize: 10, color: qualityColor, fontWeight: 700,
        background: `${qualityColor}18`, padding: '2px 7px', borderRadius: 4,
        border: `1px solid ${qualityColor}33`, minWidth: 52, textAlign: 'center',
      }}>
        {f.forecast_quality}
      </span>
    </div>
  )
}

function AnomalyRow({ a }) {
  const { T } = useTheme()
  const sev = a.severity?.toUpperCase()
  const severityColor = { HIGH: T.red, MEDIUM: T.amber, LOW: T.textSec }[sev] || T.textSec
  const modelName = ['Constant', 'Linear', 'Quadratic'][a.detected_model] || '?'
  const age = Math.floor((Date.now()/1000 - a.log_time) / 60)

  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', gap: 10,
      padding: '10px 14px', borderRadius: 8,
      background: `${severityColor}0a`,
      border: `1px solid ${severityColor}33`,
      marginBottom: 6,
    }}>
      <AlertTriangle size={13} color={severityColor} style={{ marginTop: 2, flexShrink: 0 }} />
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: 12, color: T.textPri, fontFamily: T.mono, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {a.metric_string}
        </div>
        <div style={{ fontSize: 11, color: T.textMut, marginTop: 2 }}>{a.reason}</div>
      </div>
      <div style={{ textAlign: 'right', flexShrink: 0 }}>
        <div style={{ fontSize: 11, color: severityColor, fontWeight: 700, fontFamily: T.mono }}>
          RMSE {a.rmse?.toFixed(1)}
        </div>
        <div style={{ fontSize: 10, color: T.textMut }}>{age}m ago</div>
      </div>
    </div>
  )
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function Dashboard() {
  const { T } = useTheme()
  const [metrics, setMetrics]   = useState(null)
  const [forecasts, setForecasts] = useState([])
  const [anomalies, setAnomalies] = useState([])
  const [refreshing, setRefreshing] = useState(false)
  const [lastRefresh, setLastRefresh] = useState(null)
  const [online, setOnline] = useState(null)   // null = checking, true/false = result
  const [checking, setChecking] = useState(false)

  const load = async () => {
    setRefreshing(true)
    const [m, f, a] = await Promise.all([
      fetchSystemMetrics(),
      fetchForecastAll(300),
      fetchAnomalies(),
    ])

    // If all three return null the backend is definitely offline
    if (m === null && f === null && a === null) {
      setOnline(false)
      setRefreshing(false)
      return
    }

    setOnline(true)
    setMetrics(m)
    setForecasts(f?.forecasts || [])
    // anomalies come from /internal/metadata
    setAnomalies(a?.anomalies || [])
    setLastRefresh(new Date())
    setRefreshing(false)
  }

  const retry = async () => {
    setChecking(true)
    const up = await checkBackendOnline()
    setChecking(false)
    if (up) {
      setOnline(true)
      load()
    }
  }

  useEffect(() => { load() }, [])

  useEffect(() => {
    if (!online) return
    const id = setInterval(load, 15000)
    return () => clearInterval(id)
  }, [online])

  // Compression ratio: estimated raw bytes (samples × 16 bytes each) vs actual
  // canonical bytes on disk. Shows '—' until canonical data exists so we never
  // display a misleading 0.0× on a brand-new install.
  const rawBytesEstimate = (metrics?.total_samples_ingested ?? 0) * 16
  const canonicalOnDisk  = metrics?.canonical_bytes ?? 0
  const compressionRatio = (metrics && canonicalOnDisk > 0)
    ? (rawBytesEstimate / Math.max(canonicalOnDisk, 1)).toFixed(1)
    : '—'

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden' }}>
      {/* No-backend overlay */}
      {online === false && <NoBackendModal onRetry={retry} checking={checking} />}

      <div style={{ flex: 1, overflowY: 'auto', padding: '28px 32px' }}>
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 28 }}>
          <div>
            <h1 style={{ fontSize: 22, fontWeight: 700, color: T.textPri }}>
              System Dashboard
            </h1>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 4 }}>
              {online === true && (
                <span style={{
                  display: 'flex', alignItems: 'center', gap: 4,
                  fontSize: 11, color: T.green,
                }}>
                  <Wifi size={11} /> Connected
                </span>
              )}
              {lastRefresh && (
                <span style={{ fontSize: 11, color: T.textMut }}>
                  · Last refreshed {lastRefresh.toLocaleTimeString()} · Auto-updates every 15s
                </span>
              )}
            </div>
          </div>
          <button
            onClick={load}
            disabled={refreshing}
            style={{
              display: 'flex', alignItems: 'center', gap: 7,
              padding: '8px 16px', borderRadius: 8, border: `1px solid ${T.border}`,
              background: T.bgCard, color: T.textSec, fontSize: 13, cursor: 'pointer',
            }}
          >
            <RefreshCw size={13} style={{ animation: refreshing ? 'spin 1s linear infinite' : 'none' }} />
            Refresh
          </button>
        </div>

        {/* Get Started checklist — shown when online but no chunks yet */}
        {online === true && (metrics?.total_chunks_modeled ?? 0) === 0 && (
          <GetStarted metrics={metrics} />
        )}

        {/* Primary stat grid — fills available width */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginBottom: 20 }}>
          <StatCard
            label="Active Series"
            value={metrics ? metrics.unique_series_active?.toLocaleString() : '—'}
            sub="unique time series tracked"
            color={T.cyan} icon={Activity} glow={glow.cyan}
            tooltip="The number of distinct metric streams currently being ingested and tracked in memory. Each unique combination of metric name + label set counts as one series. High cardinality (many series) increases memory usage."
          />
          <StatCard
            label="Total Samples"
            value={metrics ? (metrics.total_samples_ingested / 1_000_000).toFixed(2) + 'M' : '—'}
            sub={`${metrics?.total_chunks_modeled?.toLocaleString() ?? '—'} chunks modeled`}
            color={T.purple} icon={Database} glow={glow.purple}
            tooltip="Cumulative raw data points ingested since the last server start or checkpoint restore. Each individual float64 value pushed via /ingest_samples counts as one sample. Chunks modeled = number of compression fits completed — each chunk covers ~100 samples per series."
          />
          <StatCard
            label="Compression"
            value={metrics ? compressionRatio + 'x' : '—'}
            sub="raw vs. canonical bytes"
            color={T.green} icon={Zap} glow={glow.green}
            tooltip="How many times smaller your data is on disk compared to storing raw float64 + timestamp pairs (16 bytes each). Calculated as: (samples × 16 bytes) ÷ canonical bytes on disk. Shows — until canonical blocks exist. Expected ratio: ~53× at steady state."
          />
          <StatCard
            label="Active Anomalies"
            value={online ? anomalies.length : '—'}
            sub="in the last 30 minutes"
            color={anomalies.length > 0 ? T.red : T.green}
            icon={AlertTriangle}
            glow={anomalies.length > 0 ? glow.red : glow.green}
            tooltip="Metric series whose latest RMSE (model fit error) significantly exceeds their seasonal baseline. Detected using a rolling multiplier on historical RMSE — not a static threshold. A series must have at least 5 historical chunks before anomaly detection activates."
          />
        </div>

        {/* Secondary stats */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 14, marginBottom: 14 }}>
          {[
            {
              label: 'WAL Queue Depth',
              value: metrics?.wal_queue_depth ?? '—',
              color: metrics?.wal_queue_depth > 1000 ? T.amber : T.textPri,
              tooltip: 'Number of compressed model chunks waiting in the in-memory WAL write queue to be flushed to disk. Under normal load this stays near 0. Values above 1,000 indicate the WAL shipper cannot keep up with the compression rate — consider increasing wal_batch_size or disk I/O.',
            },
            {
              label: 'Symbols Registered',
              value: metrics?.total_symbols_registered?.toLocaleString() ?? '—',
              color: T.textPri,
              tooltip: 'Total number of unique metric name strings stored in the in-memory symbol table. Each distinct metric name (without labels) is interned to a 32-bit ID for fast lookup. This grows as new metric names are seen and never shrinks within a session.',
            },
            {
              label: 'Avg RMSE',
              value: metrics?.avg_rmse != null ? metrics.avg_rmse.toFixed(2) : '—',
              color: T.textPri,
              tooltip: 'Average Root Mean Square Error across all polynomial model fits since startup. RMSE measures how accurately the compression model reconstructs the original data — lower is more faithful. The rmse_tolerance config setting controls the maximum allowed error per fit.',
            },
            {
              label: 'Compaction Latency',
              value: metrics?.last_compaction_latency_ms != null ? metrics.last_compaction_latency_ms.toFixed(1) + 'ms' : '—',
              color: T.textPri,
              tooltip: 'Wall-clock time taken by the last ingest + compression cycle, from receiving raw samples to writing WAL chunks. Includes model fitting for all series that crossed the samples_per_segment threshold. Spikes here indicate CPU pressure or a large number of simultaneous compressions.',
            },
          ].map(s => (
            <div key={s.label} style={{
              background: T.bgCard, borderRadius: 10, padding: '14px 16px',
              border: `1px solid ${T.border}`,
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginBottom: 6 }}>
                <div style={{ fontSize: 10, color: T.textMut, letterSpacing: '0.07em', fontWeight: 600 }}>
                  {s.label.toUpperCase()}
                </div>
                <Tooltip text={s.tooltip} />
              </div>
              <div style={{ fontSize: 20, fontWeight: 700, color: s.color, fontFamily: T.mono }}>
                {s.value}
              </div>
            </div>
          ))}
        </div>

        {/* Storage breakdown panel */}
        {online === true && (() => {
          const total     = metrics?.data_dir_bytes   ?? 0
          const wal       = metrics?.wal_bytes        ?? 0
          const staging   = metrics?.staging_bytes    ?? 0
          const canonical = metrics?.canonical_bytes  ?? 0
          const index     = metrics?.index_bytes      ?? 0
          const events    = metrics?.events_bytes     ?? 0
          const registry  = metrics?.registry_bytes   ?? 0
          const memCache  = metrics?.head_cache_memory_bytes   ?? 0
          const symMeta   = metrics?.symbol_metadata_size_bytes ?? 0

          // Stacked bar segments (on-disk only)
          const segments = [
            { key: 'wal',       label: 'WAL',              bytes: wal,       color: T.cyan    },
            { key: 'staging',   label: 'Staging blocks',   bytes: staging,   color: T.purple  },
            { key: 'canonical', label: 'Canonical blocks', bytes: canonical, color: '#7c3aed' },
            { key: 'index',     label: 'LTS Index',        bytes: index,     color: T.amber   },
            { key: 'events',    label: 'Events (anomalies/regimes)', bytes: events, color: T.red },
            { key: 'registry',  label: 'Registry (patterns/causal)', bytes: registry, color: '#06b6d4' },
          ]
          const accounted = segments.reduce((s, x) => s + x.bytes, 0)
          const other     = Math.max(0, total - accounted)
          const allSegs   = other > 0
            ? [...segments, { key: 'other', label: 'Other', bytes: other, color: T.textMut }]
            : segments

          const pct = (n) => total > 0 ? Math.min(100, (n / total) * 100) : 0

          // Grid rows: on-disk locations + in-memory
          const diskRows = [
            { label: 'WAL',                   hint: 'tsdb.ai-data/wal',              bytes: wal,       color: T.cyan,    critical: wal > 1e9 },
            { label: 'Staging blocks',         hint: 'blocks/staging',                bytes: staging,   color: T.purple,  critical: false },
            { label: 'Canonical blocks',       hint: 'blocks/canonical',              bytes: canonical, color: '#7c3aed', critical: false },
            { label: 'LTS Index',              hint: 'index/',                        bytes: index,     color: T.amber,   critical: false },
            { label: 'Events',                 hint: 'events/anomalies + regimes',    bytes: events,    color: T.red,     critical: false },
            { label: 'Registry',               hint: 'registry/patterns + causal',   bytes: registry,  color: '#06b6d4', critical: false },
          ]
          const memRows = [
            { label: 'Head cache (RAM)',        hint: 'most recent model per series', bytes: memCache,  color: T.green,   critical: false },
            { label: 'Symbol table (RAM)',      hint: 'metric name strings',          bytes: symMeta,   color: T.textSec, critical: false },
          ]

          return (
            <div style={{
              background: T.bgCard, borderRadius: 10,
              border: `1px solid ${T.border}`, marginBottom: 28, overflow: 'hidden',
            }}>
              {/* Header */}
              <div style={{
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                padding: '12px 18px', borderBottom: `1px solid ${T.border}`,
              }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <Database size={14} color={T.cyan} />
                  <span style={{ fontSize: 11, color: T.textMut, letterSpacing: '0.07em', fontWeight: 700 }}>
                    STORAGE BREAKDOWN
                  </span>
                </div>
                <div style={{ display: 'flex', alignItems: 'baseline', gap: 6 }}>
                  <span style={{ fontSize: 11, color: T.textMut }}>Total on disk:</span>
                  <span style={{ fontSize: 16, fontWeight: 700, color: T.cyan, fontFamily: T.mono }}>{fmtBytes(total)}</span>
                </div>
              </div>

              {/* Stacked bar */}
              <div style={{ height: 6, display: 'flex', background: T.border }}>
                {allSegs.map(seg => (
                  <div key={seg.key} style={{
                    width: `${pct(seg.bytes)}%`, background: seg.color,
                    transition: 'width 0.6s ease',
                    minWidth: seg.bytes > 0 ? 2 : 0,
                  }} />
                ))}
              </div>

              {/* Two-column grid: Disk | Memory */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 0 }}>

                {/* Left — On-disk */}
                <div style={{ padding: '14px 18px', borderRight: `1px solid ${T.border}` }}>
                  <div style={{ fontSize: 10, color: T.textMut, fontWeight: 700, letterSpacing: '0.08em', marginBottom: 10 }}>
                    ON DISK
                  </div>
                  {diskRows.map(row => (
                    <div key={row.label} style={{
                      display: 'flex', alignItems: 'center', gap: 8,
                      padding: '5px 0', borderBottom: `1px solid ${T.border}22`,
                    }}>
                      <div style={{ width: 8, height: 8, borderRadius: 2, background: row.color, flexShrink: 0 }} />
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{ fontSize: 12, color: T.textSec, display: 'flex', alignItems: 'center', gap: 5 }}>
                          {row.label}
                          {row.critical && (
                            <span style={{ fontSize: 9, color: T.red, fontWeight: 700,
                              background: `${T.red}18`, border: `1px solid ${T.red}44`,
                              padding: '1px 5px', borderRadius: 4 }}>HIGH</span>
                          )}
                        </div>
                        <div style={{ fontSize: 10, color: T.textMut, fontFamily: T.mono }}>{row.hint}</div>
                      </div>
                      <div style={{ fontSize: 13, fontWeight: 700, color: row.bytes > 0 ? T.textPri : T.textMut, fontFamily: T.mono, flexShrink: 0 }}>
                        {fmtBytes(row.bytes)}
                      </div>
                    </div>
                  ))}
                  {/* Total row */}
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 8, paddingTop: 8, borderTop: `1px solid ${T.border}` }}>
                    <span style={{ fontSize: 11, color: T.textSec, fontWeight: 700 }}>Total</span>
                    <span style={{ fontSize: 13, fontWeight: 700, color: T.cyan, fontFamily: T.mono }}>{fmtBytes(total)}</span>
                  </div>
                </div>

                {/* Right — In-memory + write throughput */}
                <div style={{ padding: '14px 18px' }}>
                  <div style={{ fontSize: 10, color: T.textMut, fontWeight: 700, letterSpacing: '0.08em', marginBottom: 10 }}>
                    IN MEMORY
                  </div>
                  {memRows.map(row => (
                    <div key={row.label} style={{
                      display: 'flex', alignItems: 'center', gap: 8,
                      padding: '5px 0', borderBottom: `1px solid ${T.border}22`,
                    }}>
                      <div style={{ width: 8, height: 8, borderRadius: 2, background: row.color, flexShrink: 0 }} />
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div style={{ fontSize: 12, color: T.textSec }}>{row.label}</div>
                        <div style={{ fontSize: 10, color: T.textMut, fontFamily: T.mono }}>{row.hint}</div>
                      </div>
                      <div style={{ fontSize: 13, fontWeight: 700, color: row.bytes > 0 ? T.textPri : T.textMut, fontFamily: T.mono, flexShrink: 0 }}>
                        {fmtBytes(row.bytes)}
                      </div>
                    </div>
                  ))}

                  {/* Compression efficiency summary */}
                  <div style={{ marginTop: 14, paddingTop: 12, borderTop: `1px solid ${T.border}` }}>
                    <div style={{ fontSize: 10, color: T.textMut, fontWeight: 700, letterSpacing: '0.08em', marginBottom: 8 }}>
                      COMPRESSION EFFICIENCY
                    </div>
                    {[
                      {
                        label: 'Shipped → Canonical',
                        hint: 'WAL chunks vs stored models',
                        value: canonicalOnDisk > 0
                          ? (rawBytesEstimate / Math.max(canonicalOnDisk, 1)).toFixed(1) + '×'
                          : '—',
                        color: T.green,
                      },
                      {
                        label: 'Samples ingested',
                        hint: 'total across all series',
                        value: metrics?.total_samples_ingested != null
                          ? (metrics.total_samples_ingested >= 1e6
                              ? (metrics.total_samples_ingested / 1e6).toFixed(2) + 'M'
                              : metrics.total_samples_ingested.toLocaleString())
                          : '—',
                        color: T.textPri,
                      },
                      {
                        label: 'Chunks modeled',
                        hint: 'polynomial compression fits',
                        value: metrics?.total_chunks_modeled?.toLocaleString() ?? '—',
                        color: T.purple,
                      },
                    ].map(row => (
                      <div key={row.label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 6 }}>
                        <div>
                          <div style={{ fontSize: 12, color: T.textSec }}>{row.label}</div>
                          <div style={{ fontSize: 10, color: T.textMut }}>{row.hint}</div>
                        </div>
                        <div style={{ fontSize: 13, fontWeight: 700, color: row.color, fontFamily: T.mono }}>{row.value}</div>
                      </div>
                    ))}
                  </div>
                </div>

              </div>
            </div>
          )
        })()}

        {/* Two-column: Forecasts + Anomalies — fills remaining height */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 24 }}>
          {/* Forecast panel */}
          <div style={{ background: T.bgCard, borderRadius: 12, padding: '20px', border: `1px solid ${T.border}` }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
              <TrendingUp size={15} color={T.cyan} />
              <span style={{ fontSize: 14, fontWeight: 600, color: T.textPri }}>5-Minute Forecasts</span>
              {online === true && forecasts.length > 0 && (
                <span style={{
                  marginLeft: 'auto', fontSize: 10, color: T.textMut,
                  background: T.bgPanel, border: `1px solid ${T.border}`,
                  padding: '1px 7px', borderRadius: 8,
                }}>{forecasts.length} metrics</span>
              )}
            </div>
            {online === null && (
              <div style={{ fontSize: 12, color: T.textMut, textAlign: 'center', padding: '24px 0', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
                <RefreshCw size={13} style={{ animation: 'spin 1s linear infinite' }} /> Connecting…
              </div>
            )}
            {online === true && forecasts.length === 0 && (
              <div style={{ fontSize: 12, color: T.textMut, textAlign: 'center', padding: '24px 0' }}>
                No forecast data available
              </div>
            )}
            {forecasts.map(f => <ForecastRow key={f.metric} f={f} />)}
          </div>

          {/* Anomalies panel */}
          <div style={{ background: T.bgCard, borderRadius: 12, padding: '20px', border: `1px solid ${T.border}` }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
              <AlertTriangle size={15} color={T.amber} />
              <span style={{ fontSize: 14, fontWeight: 600, color: T.textPri }}>Recent Anomalies</span>
            </div>
            {online === null && (
              <div style={{ fontSize: 12, color: T.textMut, textAlign: 'center', padding: '24px 0', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
                <RefreshCw size={13} style={{ animation: 'spin 1s linear infinite' }} /> Connecting…
              </div>
            )}
            {online === true && anomalies.length === 0 && (
              <div style={{ fontSize: 12, color: T.green, textAlign: 'center', padding: '24px 0' }}>
                ✓ No anomalies detected
              </div>
            )}
            {anomalies.map((a, i) => <AnomalyRow key={i} a={a} />)}
          </div>
        </div>
      </div>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  )
}
