apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tsdb-scraper.fullname" . }}
  namespace: {{ include "tsdb-scraper.namespace" . }}
  labels:
    {{- include "tsdb-scraper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tsdb-scraper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tsdb-scraper.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "tsdb-scraper.imagePullSecrets" . | nindent 6 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: scraper
          image: {{ include "tsdb-scraper.image" . | quote }}
          imagePullPolicy: {{ include "tsdb-scraper.imagePullPolicy" . }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: TSDB_INGESTOR_URL
              value: {{ .Values.ingestorUrl | quote }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tsdb-storage
              mountPath: {{ .Values.persistence.mountPath | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tsdb-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
